services:
 web:
  image: nginx:latest
  container_name: nginx
  restart: always
  volumes:
   - ./api:/api
   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  networks:
    - projetox
  links:
  - php

 php:
  image: php:8.1-fpm
  build:
    context: .
    dockerfile: ./Dockerfile
  container_name: php-fpm
  expose:
    - "9000"
  networks:
    - projetox
  volumes:
    - "./api:/api"

 db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: devsecret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    ports:
      - "54320:5432"
      
networks:
  projetox:
  